kmshub/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("users_app.urls")),
        path("", include("users_app.url_admin")),
        path("", include("users_app.url_general")),
        path("", include("users_app.url_secretariat")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

users_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .url_admin import urlpatterns as admin_urls
from .url_general import urlpatterns as general_urls
from .url_secretariat import urlpatterns as secretariat_urls

urlpatterns = (
    [
        path("activate/<uidb64>/<token>", views.activate, name="activate"),
        path("login/", views.login, name="login"),
        path("sign-up", views.register, name="sign-up"),
        path("logout/", views.logout_view, name="logout"),
        path("update-password/", views.update_password, name="update-password"),
        path("enter-email?/", views.enter_email, name="email"),
        path(
            "reset-pass?/<uidb64>/<token>",
            views.reset_pass_email,
            name="reset-pass-confirm",
        ),
        path("new-password/", views.reset_password, name="new-pass"),
        # Include admin URLs under a specific path, for example 'admin/'
        path("admin/", include(admin_urls)),
        path("general/", include(general_urls)),
        path("secretariat/", include(secretariat_urls)),
        path(
            "technology-generated?/<str:name>/",
            views.display_tech_generated,
            name="tech_generated",
        ),
        path("adding-technology-generated/", views.add_tech_generated, name="add_tech"),
        path(
            "technology-adaptor?/<str:name>/",
            views.display_tech_adaptor,
            name="tech_adaptor",
        ),
        path("adding-technology-adaptor?/", views.add_tech_adaptor, name="add_adaptor"),
        path(
            "technology-generated?/individual-technology-generated/<int:id>/",
            views.individual_tech_gen,
            name="ind_tech_gen",
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

users_app/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.db.models import F
from django.urls import reverse

from embed_video.fields import EmbedVideoField


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        print("Creating user with custom manager")
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)

        # Check if a user with the same email exists
        if self.model.objects.filter(email=email).exists():
            raise ValueError("A user with this email already exists")

        user = self.model(email=email, user_type=CustomUser.GENERAL, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_secretariat(self, email, password=None, **extra_fields):
        extra_fields.setdefault("user_type", CustomUser.SECRETARIAT)
        return self._create_user(email, password, **extra_fields)

    def create_expert(self, email, password=None, **extra_fields):
        extra_fields.setdefault("user_type", CustomUser.EXPERT)
        return self._create_user(email, password, **extra_fields)

    def _create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)

        # Check if a user with the same email exists
        if self.model.objects.filter(email=email).exists():
            raise ValueError("A user with this email already exists")

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


class CustomUser(AbstractUser):
    EXPERT = "expert"
    SECRETARIAT = "secretariat"
    GENERAL = "general"
    ADMIN = "admin"
    CMI = "cmi"

    USER_TYPES = [
        (EXPERT, "Expert"),
        (SECRETARIAT, "Secretariat"),
        (GENERAL, "General User"),
        (ADMIN, "Admin User"),
        (CMI, "CMI"),
    ]

    email = models.EmailField(max_length=255, unique=True, blank=True)
    institution = models.CharField(max_length=255, null=True, blank=True)
    position = models.CharField(max_length=255, null=True, blank=True)
    date_birth = models.DateField(null=True, blank=True)  # Date of birth
    sex = models.CharField(max_length=20, null=True, blank=True)  # Sex of the user
    gender = models.CharField(max_length=20, null=True, blank=True)  # Gender identity
    specialization = models.CharField(
        max_length=255, null=True, blank=True
    )  # Area of specialization
    highest_educ = models.CharField(
        max_length=255, null=True, blank=True
    )  # Highest education attained
    contact_num = models.CharField(
        max_length=15, null=True, blank=True
    )  # Contact number
    user_type = models.CharField(
        max_length=20, choices=USER_TYPES, null=True, blank=True
    )
    date_created = models.DateField(default=timezone.now, null=True, blank=True)

    # Set username to be nullable and unique to avoid conflicts
    username = models.CharField(max_length=150, unique=True, blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        # Ensure username is set to None before saving if it's an empty string
        if self.username == "":
            self.username = None
        super().save(*args, **kwargs)


class Profile(models.Model):
    profile_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to="profiles_img/", null=True)

    class Meta:
        db_table = "tbl_profile"


class Commodity(models.Model):
    commodity_id = models.AutoField(primary_key=True)
    commodity_name = models.CharField(max_length=100)
    description = models.TextField()
    resources_type = models.CharField(max_length=100)
    commodity_img = models.ImageField(upload_to="commodities/", null=True)
    date_created = models.DateTimeField(default=timezone.now, null=True)
    date_edited = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=255, default="Approved")
    latitude = models.DecimalField(
        max_digits=11, decimal_places=8, null=True, blank=True
    )
    longitude = models.DecimalField(
        max_digits=11, decimal_places=8, null=True, blank=True
    )

    def save(self, *args, **kwargs):
        if self.pk:
            self.date_edited = timezone.now().date()
        super(Commodity, self).save(*args, **kwargs)

    def __str__(self):
        return self.commodity_name

    class Meta:
        db_table = "tbl_commodity"


class KnowledgeResources(models.Model):
    knowledge_id = models.AutoField(primary_key=True)
    knowledge_title = models.CharField(max_length=255)
    knowledge_description = models.TextField()
    status = models.CharField(max_length=255, default="Approved")
    date_created = models.DateTimeField(default=timezone.now, null=True)

    class Meta:
        db_table = "tbl_knowledge"


class About(models.Model):
    about_id = models.AutoField(primary_key=True)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        db_table = "tbl_about"


class AboutFooter(models.Model):
    about_footer_id = models.AutoField(primary_key=True)
    content_footer = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        db_table = "tbl_about_footer"


class Discussion(models.Model):
    discussion_id = models.AutoField(primary_key=True)
    discussion_title = models.CharField(max_length=255)
    discussion_question = models.TextField()
    commodity_id = models.ManyToManyField(Commodity, related_name="tag_commodity")
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    bookmark = models.ManyToManyField(
        CustomUser, blank=True, related_name="user_bookmarked_discussion"
    )
    date_posted = models.DateField(default=timezone.now, null=True)

    class Meta:
        db_table = "tbl_discussion&forum"


class DiscussionRating(models.Model):
    discussion_rating_id = models.AutoField(primary_key=True)
    rated_by = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True
    )  # Link to user who reacted
    discussion = models.ForeignKey(
        Discussion, on_delete=models.CASCADE
    )  # Link to the reacted discussion
    rating = models.IntegerField(default=1)

    class Meta:
        db_table = "tbl_discussion_rating"


class DiscussionReport(models.Model):
    discussion_report_id = models.AutoField(primary_key=True)
    discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)
    report_category = models.CharField(max_length=255)
    report_content = models.TextField(null=True)
    reported_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date_reported = models.DateField(default=timezone.now)

    class Meta:
        db_table = "tbl_discussion_report"


class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    commentor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)
    comment_content = models.TextField()
    react = models.ManyToManyField(
        CustomUser, blank=True, related_name="user_react_comment"
    )
    date_commented = models.DateField(default=timezone.now)

    class Meta:
        db_table = "tbl_comment"


class CommentRating(models.Model):
    comment_rating_id = models.AutoField(primary_key=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    rating = models.IntegerField(default=1)
    rated_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "tbl_comment_rating"


class CommentReport(models.Model):
    comment_report_id = models.AutoField(primary_key=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    report_category = models.CharField(max_length=255)
    report_content = models.TextField(null=True)
    reported_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    date_reported = models.DateField(default=timezone.now)

    class Meta:
        db_table = "tbl_comment_report"


class SearchFrequency(models.Model):
    search_id = models.AutoField(primary_key=True)
    search_term = models.CharField(max_length=255)
    frequency = models.IntegerField(default=1)
    date_searched = models.DateField(default=timezone.now)

    class Meta:
        db_table = "tbl_search_analytics"

    def update_or_create_instance(self, search_term):
        today = timezone.now().date()  # Define today's date
        existing_instances = SearchFrequency.objects.filter(search_term=search_term)

        if existing_instances.exists():
            instance_with_today_date = existing_instances.filter(
                date_searched=today
            ).first()

            if instance_with_today_date:
                # If an instance with today's date exists, increment its frequency
                instance_with_today_date.frequency += 1
                instance_with_today_date.save()
            else:
                # Create a new instance with today's date and frequency 1
                SearchFrequency.objects.create(
                    search_term=search_term, frequency=1, date_searched=today
                )
        else:
            # If no instance exists, create a new instance with today's date and frequency 1
            SearchFrequency.objects.create(
                search_term=search_term, frequency=1, date_searched=today
            )

users_app/templates/accounts/admin/admin_about.html
{% extends 'base/admin.html' %}
{% load embed_video_tags %}
{% load static %}
{% block title %}
  Admin About
{% endblock %}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'style/admin.css/admin.about.css' %}" />
  <!-- CSS -->
  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
  <br />
  <div class="main-content" id="main-content">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="button-container-head">
            <button type="button" id="about-page-btn" style="background-color: #0C356A; color: #fff; border: 0; border-radius: 3px; padding: 5px; font-weight: bold;">About Page Component</button>
            <button type="button" id="about-footer-btn" style="background-color: #0C356A; color: #fff; border: 0; border-radius: 3px; padding: 5px; font-weight: bold;">About Footer Component</button>
            <button type="button" id="video-btn" style="background-color: #0C356A; color: #fff; border: 0; border-radius: 3px; padding: 5px; font-weight: bold;">"How To Use (Video)" Component</button>
          </div>
        </div>
      </div>
      <hr style="color: black;" />

      <div class="about-page" id="about-page">
        <h3 style="font-weight:bold;">ADMIN 'ABOUT PAGE'</h3>

        <div class="row">
          <div class="col-lg-12" style="margin-top:20px; width: 100%;">
            <form action="{{form_action}}" method="post">
              {% csrf_token %}
              <textarea name="content" id="about-page-textarea">
                {% if about_content %}
                  <!-- Display existing content -->
                  {% for content_data in about_content %}
                    {{ content_data.content }}
                  {% endfor %}
                {% else %}
                  <span>No content</span>
                {% endif %}
              </textarea>
              <button type="submit" class="btn btn-success" style="float:right; margin-top:20px;">Update</button>
            </form>
          </div>
        </div>
      </div>

      <div class="about-footer" id="about-footer">
        <h3 style="font-weight:bold;">ADMIN 'ABOUT FOOTER'</h3>

        <div class="row">
          <div class="col-lg-12" style="margin-top:20px; width: 100%;">
            <form action="{{form_action_footer}}" method="post">
              {% csrf_token %}
              <textarea name="content_footer" id="about-footer-textarea">
                {% if footer_content %}
                  <!-- Display existing content -->
                  {% for footer_data in footer_content %}
                    {{ footer_data.content_footer }}
                  {% endfor %}
                {% else %}
                  <span>No content</span>
                {% endif %}
              </textarea>
              <button type="submit" class="btn btn-success" style="float:right; margin-top:20px;">Update</button>
            </form>
          </div>
        </div>
      </div>

      <div class="video-component" id="video-component">
        <div class="header d-flex justify-content-between align-items-center">
          <h3 style="font-weight:bold;">ADMIN 'HOW TO USE' VIDEO</h3>
          <button type="button" title="Upload" style="background-color: #0C356A; color: #fff; border: 0; border-radius: 3px; padding: 5px; font-weight: bold;" data-toggle="modal" data-target="#uploadvideoModal">Upload Video</button> 
        </div>

        <div class="row">
          <div class="col-lg-12" style="margin-top:20px; width: 100%;">
            {% video videos.url '1000x700'%}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% include 'accounts/admin/modals/video/upload.html' %}
{% endblock %}

{% block script %}
  <!-- JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
  {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'success' %}
        <script>
          // Display SweetAlert success message
          Swal.fire({
            icon: 'success',
            title: 'Success!',
            text: '{{ message }}'
          })
        </script>
      {% endif %}
    {% endfor %}
  {% endif %}

  <script>
    $(document).ready(function () {
      $('#about-page textarea').summernote({
        height: 300,
        placeholder: 'Write here...',
        toolbar: [
          ['style', ['style', 'bold', 'italic', 'underline', 'clear']],
          ['font', ['strikethrough', 'superscript', 'subscript']],
          ['fontsize', ['fontsize']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['insert', ['link', 'picture', 'video']],
          ['insert', ['hr']],
          ['insert', ['table']],
          ['misc', ['undo', 'redo']],
          ['mybutton', ['codeview']],
          ['mybutton', ['spellchecker']],
          ['mybutton', ['cut', 'copy', 'paste', 'plainpaste', 'wordpaste']],
          ['mybutton', ['link', 'unlink', 'anchor']]
        ],
        buttons: {
          spellchecker: function (context) {
            var ui = $.summernote.ui
            // create button
            var button = ui.button({
              contents: '<i class="fa fa-magic"/>',
              tooltip: 'Spell Checker',
              click: function () {
                context.invoke('editor.spellCheck')
              }
            })
            return button.render()
          }
        },
        styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'], // Include more styles as needed
        fontSizes: ['8', '9', '10', '11', '12', '14', '18', '24', '36'], // Add your desired font sizes
        colors: [['#000000', '#ffffff', '#e0e0e0', '#b0b0b0', '#808080', '#404040', '#ff0000', '#ff9900', '#ffff00', '#00ff00', '#00ffff', '#0000ff', '#9900ff', '#ff00ff', '#f7f7f7', '#ccc']] // Add your desired color palette
      })
    })
    
    $(document).ready(function () {
      $('#about-footer textarea').summernote({
        height: 300,
        placeholder: 'Write here...',
        toolbar: [
          ['style', ['style', 'bold', 'italic', 'underline', 'clear']],
          ['font', ['strikethrough', 'superscript', 'subscript']],
          ['fontsize', ['fontsize']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['insert', ['link', 'picture', 'video']],
          ['insert', ['hr']],
          ['insert', ['table']],
          ['misc', ['undo', 'redo']],
          ['mybutton', ['codeview']],
          ['mybutton', ['spellchecker']],
          ['mybutton', ['cut', 'copy', 'paste', 'plainpaste', 'wordpaste']],
          ['mybutton', ['link', 'unlink', 'anchor']]
        ],
        buttons: {
          spellchecker: function (context) {
            var ui = $.summernote.ui
            // create button
            var button = ui.button({
              contents: '<i class="fa fa-magic"/>',
              tooltip: 'Spell Checker',
              click: function () {
                context.invoke('editor.spellCheck')
              }
            })
            return button.render()
          }
        },
        styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'], // Include more styles as needed
        fontSizes: ['8', '9', '10', '11', '12', '14', '18', '24', '36'], // Add your desired font sizes
        colors: [['#000000', '#ffffff', '#e0e0e0', '#b0b0b0', '#808080', '#404040', '#ff0000', '#ff9900', '#ffff00', '#00ff00', '#00ffff', '#0000ff', '#9900ff', '#ff00ff', '#f7f7f7', '#ccc']] // Add your desired color palette
      })
    })
    
    document.addEventListener('DOMContentLoaded', function () {
      var aboutPage = document.getElementById('about-page')
      var aboutFooter = document.getElementById('about-footer')
      var videoComponent = document.getElementById('video-component')

      
    
      var pageBtn = document.getElementById('about-page-btn')
      var footerBtn = document.getElementById('about-footer-btn')
      var videoBtn = document.getElementById('video-btn')
    
      hideAllTablesExcept(aboutPage)
    
      pageBtn.addEventListener('click', function () {
        aboutPage.style.display = 'block'
        hideAllTablesExcept(aboutPage)
      })
    
      footerBtn.addEventListener('click', function () {
        aboutFooter.style.display = 'block'
        hideAllTablesExcept(aboutFooter)
      })

      videoBtn.addEventListener('click', function () {
        videoComponent.style.display = 'block'
        hideAllTablesExcept(videoComponent)
      })
    
      function hideAllTablesExcept(exceptTable) {
        var tables = [aboutPage, aboutFooter, videoComponent]
        tables.forEach(function (table) {
          if (table !== exceptTable) {
            table.style.display = 'none'
          }
        })
      }
    })
  </script>
{% endblock %}

users_app/templates/accounts/admin/admin_discussion.html
{% extends 'base/admin.html' %}
{% load static %}
{% block title %}
  Admin Discussion Management
{% endblock %}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'style/admin.css/admin.commodities.css' %}" />
{% endblock %}

{% block content %}
  <br />
  <div class="main-content" id="main-content">
    <div class="container">
      <h3 style="font-weight:bold;">ADMIN DISCUSSION MANAGEMENT</h3>
      <hr style="color: black;" />
      <div class="card-container">
        <div class="animated fadeIn">
          <div class="row">
            <div class="col-lg-3 col-md-6">
              <div class="card">
                <div class="card-body">
                  <div class="stat-widget-five">
                    <div class="stat-icon dib flat-color-cmi">
                      <span class="mdi mdi-note-plus"></span>
                    </div>
                    <div class="stat-content">
                      <div class="text-left dib">
                        <div class="stat-text">
                          <span class="count">
                            {% if total_posts_today %}
                              {{ total_posts_today }}
                            {% else %}
                              0
                            {% endif %}
                          </span>
                        </div>
                        <div class="stat-heading">
                          <span>Daily Posts</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-lg-3 col-md-6">
              <div class="card">
                <div class="card-body">
                  <div class="stat-widget-five">
                    <div class="stat-icon dib flat-color-1">
                      <span class="mdi mdi-post"></span>
                    </div>
                    <div class="stat-content">
                      <div class="text-left dib">
                        <div class="stat-text">
                          <span class="count">
                            {% if total_discussions %}
                              {{ total_discussions }}
                            {% else %}
                              0
                            {% endif %}
                          </span>
                        </div>
                        <div class="stat-heading">
                          <span>Total Posts</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br />
      <div class="button-container-head">
        <a href="{% url 'admin-search' %}" id="approved-data-button" style="background-color: #0C356A; color: #fff; border: 0; border-radius: 3px; padding: 5px; font-weight: bold;">Search Analytics</a>
        <a href="{% url 'admin-reaction' %}" id="approved-data-button" style="background-color: #0C356A; color: #fff; border: 0; border-radius: 3px; padding: 5px; font-weight: bold;">Reactions Analytics</a>
        <a href="{% url 'admin-comment' %}" id="approved-data-button" style="background-color: #0C356A; color: #fff; border: 0; border-radius: 3px; padding: 5px; font-weight: bold;">Comments Analytics</a>
      </div>
      <hr />
      <div class="table-container">
        <table id="discussionTable" class="discussion-table table table-bordered">
          <thead style="color: #fff; font-size: 13px; background-color: #0C356A; font-weight: bolder;">
            <tr>
              <th>ID</th>
              <th>Title</th>
              <th>Question</th>
              <th>Tagged Commodity</th>
              <th>Date</th>
              <th>Likes</th>
              <th>Dislikes</th>
              <th>Comments</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody style="font-size: 12px;">
            {% for forum in forums %}
              <tr>
                <td>{{ forum.discussion_id }}</td>
                <td>{{ forum.discussion_title }}</td>
                <td>{{ forum.discussion_question }}</td>
                <td>
                  {% for commodity in forum.commodity_id.all %}
                    <span style="background-color: #0C356A; color: white;">{{ commodity.commodity_name }}</span>
                  {% endfor %}
                </td>
                <td>{{ forum.date_posted }}</td>
                <td>
                  {% if forum.reaction_set.exists %}
                    {% for reaction in forum.reaction_set.all %}
                      {{ reaction.like }}
                    {% endfor %}
                  {% else %}
                    0
                  {% endif %}
                </td>
                <td>
                  {% if forum.reaction_set.exists %}
                    {% for reaction in forum.reaction_set.all %}
                      {{ reaction.dislike }}
                    {% endfor %}
                  {% else %}
                    0
                  {% endif %}
                </td>
                <td>{{ forum.comment_set.count }}</td>
                <td>
                  <a data-placement="top" data-toggle="tooltip" title="delete" href="/delete-discussion/{{ forum.discussion_id }}" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    $(document).ready(function () {
      let table = $('#discussionTable').DataTable({
        language: {
          lengthMenu: '_MENU_',
          search: '',
          searchPlaceholder: 'Search...'
        },
        lengthMenu: [
          [3, 5, 7, 10, 25, -1],
          [3, 5, 7, 10, 25, 'All']
        ],
        paging: true,
        lengthChange: true,
        autoWidth: false,
        bInfo: true,
        bSort: true,
        responsive: true,
        buttons: [
          {
            text: 'CSV',
            extend: 'csv'
          },
          {
            text: 'PDF',
            extend: 'pdf'
          }
        ],
        dom: '<"row"<"col-md-1"l><"col-md-8"B><"col-md-3"f>>' + '<"row"<"col-md-12"tr>>' + '<"row"<"col-md-5"i><"col-md-7"p>>'
      })
    })
  </script>
  {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'success' %}
        <script>
          // Display SweetAlert success message
          Swal.fire({
            icon: 'success',
            title: 'Success!',
            text: '{{ message }}'
          })
        </script>
        {% else %}
        <script>
          // Display SweetAlert success message
          Swal.fire({
            icon: 'error',
            title: 'Error!',
            text: '{{ message }}'
          })
        </script>
      {% endif %}
    {% endfor %}
  {% endif %}
{% endblock %}